### ISSUE TITLE
Modular Blueprints not appearing in Admin

### ISSUE THREAD

**Issue by sparrow925** [getgrav/grav-theme-quark#140] opened 2020-02-03 21:12 UTC
Apologies if I'm missing something basic, but this used to work and it no longer does for me. After a few days of tinkering and reading through the docs, I'm stumped.

This is an example I tried using a fresh Quark download today, and I do not see the Admin tabs that the modular blueprint file should be adding.

**File structure**
```
user
|   
+---pages
|   \---01.home
|       |   modular.md
|       |   
|       \---01._hero
|               header.jpg
|               hero.md
|               
\---themes
    \---quark
        \---blueprints
            \---modular
                    hero.yaml
```

**Content of the .md files:**
_modular.md_
```
---
title: Home
content:
    items: '@self.modular'
body_classes: 'title-h1h2 header-transparent'
menu: Home
onpage_menu: false
---
```

_hero.md_
```
---
title: 'Homepage Top Image'
menu: Top
hero_classes: 'text-light title-h1h2 parallax overlay-dark-gradient hero-fullscreen'
hero_image: header.jpg
---
```

_Edited for filetree formatting..._

**Comment by mahagr** [comment] 2020-02-04 08:09
Try `blueprints/pages/modular/hero.yaml`

**Comment by sparrow925** [comment] 2020-02-04 17:52
No change, shoot.

I noticed that `blueprints/default.yaml` is having the intended effect on the admin page. When moved to `blueprints/pages/default.yaml` it does not. This is consistent with some other troubleshooting threads I found. The page folder is discussed as necessary for adding blueprints in `user/blueprints` but not in `theme/blueprints`.

I also tried to move the modular files to `user/blueprints/pages/modular` and that doesn't work either. Note that `user/blueprints/pages/default.yaml` *does* work.

**Comment by paulhibbitts** [comment] 2020-02-04 18:01
Hi @sparrow925 , I use a few modular blueprints for my Quark Open Publishing theme in `blueprints/modular`:
https://github.com/hibbitts-design/grav-theme-quark-open-publishing/tree/master/blueprints/modular

Perhaps the issue is with your blueprint? You could post it here just in case.

**Comment by sparrow925** [comment] 2020-02-04 18:44
Thanks for the examples @paulhibbitts! I'll dive in and try to find differences. For giggles, I changed the `@extends` to match your blueprints exactly (with the `type` and `context` breakouts) but saw no change. 

In the meantime, here is the blueprint file I'm using as my test subject... it's one of the default Quark modular blueprints. I've tried to strip this issue down to the bare bones and am using a fresh copy of Grav and Quark to figure out what the heck is happening. The issue is happening on both my Mac and PC dev environments so I'm tempted to rule out an external issue. But... Is anyone else having issues with this in a fresh Grav/Quark instance?

`title: Hero
'@extends': default

form:
  fields:
    tabs:
      fields:
        buttons:
          type: tab
          title: Hero
          fields:
            header.hero_classes:
              type: text
              label: Hero Classes
              markdown: true
              description: 'There are several Hero class options that can be listed here (space separated):<br />`text-light`, `text-dark`, `title-h1h2`, `parallax`, `overlay-dark-gradient`, `overlay-light-gradient`, `overlay-dark`, `overlay-light`, `hero-fullscreen`, `hero-large`, `hero-medium`, `hero-small`, `hero-tiny`<br />Please consult the [Quark documentation](https://github.com/getgrav/grav-theme-quark#hero-options) for more details.'
            header.hero_image:
              type: filepicker
              label: Hero Image
              preview_images: true
              description: 'If not specified, this defaults to the first image found in the page''s folder'
`

**Comment by paulhibbitts** [comment] 2020-02-04 19:13
Thanks, I just noticed this... change `01._hero` folder name to `_hero` and see if that works. That should then define it as a proper `modular` page.

BTW, for issues like this, the Discord chat or getgrav.org Forum is a better place - happy to try to help you in either of those places if the above does not address your issue.

Cheers,
Paul

**Comment by sparrow925** [comment] 2020-02-04 21:47
I've tried that as well, no dice. I made a post in the Grav forum as well, [here](https://discourse.getgrav.org/t/looking-for-example-of-blueprints-for-modular-pages/11307). Happy to continue there.

**Comment by paulhibbitts** [comment] 2020-02-04 21:53
Great, could you please close the issue and we will continue there🙂

**Closed** 2020-02-04 22:04 UTC
